import Head from "next/head";
import { BsCodeSlash, BsFillEmojiSmileFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillFacebook,
  AiFillBank,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/profilepicture.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import Typical from "react-typical";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Hassan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyHassan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="Hassan's Resumee.pdf"
                  download="Hassan Hassan.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Hello I'm Hassan
            </h2>
            <h1 className="text-2xl py-2 dark:text-white md:text-3xl">
              <Typical
                loop={Infinity}
                steps={[
                  "Enthusiastic Dev 😎",
                  10000,
                  "Full stack Developer 💻",
                  10000,
                  "Flutter Dev 📱",
                  10000,
                  "Cross Platform Dev 🔴",
                  1000,
                  "React/React Native 🌐",
                  1000,
                ]}
              />
            </h1>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              "Knack of building applications with front and back end
              operations.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://web.facebook.com/turi.toori/">
                <AiFillFacebook />
              </a>
              <a href="https://www.instagram.com/_hassanturi/">
                <AiFillInstagram />
              </a>
              <a href="https://www.linkedin.com/in/hassan-15a502164/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/hassan1105">
                <AiFillGithub />
              </a>
            </div>
            <div className=" transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 border-double border-4 border-teal-500">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-600 flex-1">
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Full stack web and mobile developer with background knowledge of
              React js, Flutter and dart language, along with a knack of
              building applications with utmost efficiency. Strong professional
              with a BSC willing to be an asset for an organization.",
            </p>
            <div className="text-center shadow-lg p-10">
              <p className="text-gray-800 py-1 dark:text-white">
                Full Stack web and mobile development
              </p>
              <p className="text-gray-800 py-1 dark:text-white">
                Interactive Front End as per the design
              </p>
              <p className="text-gray-800 py-1 dark:text-white">
                React and React Native
              </p>
              <p className="text-gray-800 py-1 dark:text-white">Flutter dev</p>
              <p className="text-gray-800 py-1 dark:text-white">
                Managing database
              </p>
            </div>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-600 flex-1">
              <AiFillBank className=" mx-auto text-5xl" />

              <h3 className="text-lg font-medium pt-8 pb-2  dark:text-white">
                Education
              </h3>
              <p className="py-2 dark:text-white">Recent Graduate</p>
              <h2 className="py-4 text-teal-600 font-bold dark:text-white">
                Bahria University Islamabad
              </h2>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Software Engineering
              </h4>
              <p className="text-gray-800 py-1 dark:text-white">2018-2022</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600 flex-1">
              <BsCodeSlash className="mx-auto text-5xl" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white ">
                Programming Skills
              </h3>

              <h4 className="text-gray-800 py-1 dark:text-white">JavaScript</h4>
              <p className="text-gray-800 py-1 dark:text-white">React JS</p>
              <p className="text-gray-800 py-1 dark:text-white">Flutter</p>
              <p className="text-gray-800 py-1 dark:text-white">Dart</p>
              <p className="text-gray-800 py-1 dark:text-white">HTML</p>
              <p className="text-gray-800 py-1 dark:text-white">Firebase</p>
              <p className="text-gray-800 py-1 dark:text-white">C#</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600 flex-1">
              <BsFillEmojiSmileFill className="mx-auto text-5xl" />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white ">
                Interest
              </h3>
              <h4 className="py-4 text-teal-600 dark:text-white">Reading</h4>
              <p className="py-2 dark:text-white">
                Apart from being a tech enthusiast and a code writer, i also
                love to read books and it leads to the all-round development of
                my brain and personalit.
              </p>
              <h4 className="py-4 text-teal-600 dark:text-white">
                Competitive Gaming
              </h4>
              <p className="py-2 dark:text-white">
                I like to challenge my reflexes a lot while competing in games,
                pushing the rank and having interactive gaming sessions excites
                me the most.{" "}
              </p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div className="text-center text-1xl shadow-lg  bg-slate-400 p-10 rounded-xl my-10 dark:bg-gray-600 flex-1">
            <Typical loop={Infinity} steps={["Get In Touch", 1000]} />
            <a href="mailto:hassanisrar15@gmail.com"> <Typical loop={Infinity} steps={["Hassanisrar15@gmail.com 📧", 1000]} /></a>
           
          </div>
        </section>
        
      </main>
    </div>
  );
}
